spring.application.name=hazard-tracker

# database connection url
spring.datasource.url = jdbc:postgresql://localhost:5432/hazard_db

# database cred
spring.datasource.username = postgres
spring.datasource.password = password

#hibernate settings for update
spring.jpa.hibernate.ddl-auto = update

#show sql in console
spring.jpa.show-sql = true
